In [1]:
import torch
from ReplayBuffer import ReplayBuffer
# Example usage, show correct alignment during replay
episodes = 20
stored_episodes = 8
samples_per_episode = 40
device = 'cuda'

buffer = ReplayBuffer(stored_episodes, samples_per_episode, device)

for i in range(episodes):
    state = torch.tensor(i * episodes + 0.1, device=device)
    action = torch.tensor(i * episodes + 0.2, device=device)
    reward = torch.tensor(i * episodes + 0.3, device=device)
    target = torch.tensor(i * episodes + 0.4, device=device)
    for k in range (samples_per_episode):
        buffer.add(state, action, reward, target)
        state += 1.0
        action += 1.0
        reward += 1.0
        target +=1.0

    if (buffer.size >= 8):
        batch_size = 4
        seq_length = 10
        batch = buffer.random_sample(batch_size, seq_length)

        for b in batch:
            print(b)

tensor([[127.1000, 128.1000, 129.1000, 130.1000, 131.1000, 132.1000, 133.1000,
         134.1000, 135.1000, 136.1000, 137.1000],
        [ 76.1000,  77.1000,  78.1000,  79.1000,  80.1000,  81.1000,  82.1000,
          83.1000,  84.1000,  85.1000,  86.1000],
        [ 11.1000,  12.1000,  13.1000,  14.1000,  15.1000,  16.1000,  17.1000,
          18.1000,  19.1000,  20.1000,  21.1000],
        [156.1000, 157.1000, 158.1000, 159.1000, 160.1000, 161.1000, 162.1000,
         163.1000, 164.1000, 165.1000, 166.1000]], device='cuda:0')
tensor([[127, 128, 129, 130, 131, 132, 133, 134, 135, 136],
        [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [156, 157, 158, 159, 160, 161, 162, 163, 164, 165]], device='cuda:0',
       dtype=torch.int32)
tensor([[136.3000],
        [ 85.3000],
        [ 20.3000],
        [165.3000]], device='cuda:0')
tensor([[136.4000],
        [ 85.4000],
        [ 20.4000],
        [165.4000]], dev

In [1]:
import torch
from ReplayBuffer import ReplayBuffer
# Example usage, show correct alignment during evaluation
episodes = 5
stored_episodes = 3
samples_per_episode = 30
seqence_length = 8
device = 'cuda'

buffer = ReplayBuffer(stored_episodes, samples_per_episode, device)

for i in range(episodes):
    state = torch.tensor(i * episodes + 0.1, device=device)
    action = torch.tensor(i * episodes + 0.2, device=device)
    reward = torch.tensor(i * episodes + 0.3, device=device)
    target = torch.tensor(i * episodes + 0.4, device=device)
    for k in range (samples_per_episode):
        state_series, action_series = buffer.getInput(seqence_length)
        print("-------------------")
        print(state_series)
        print(action_series)
        buffer.add(state, action, reward, target)
        state += 1.0
        action += 1.0
        reward += 1.0
        target += 1.0

(tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0'))
(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1000],
       device='cuda:0'), tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2000],
       device='cuda:0'))
(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 1.1000],
       device='cuda:0'), tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2000, 1.2000],
       device='cuda:0'))
(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 1.1000, 2.1000],
       device='cuda:0'), tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2000, 1.2000, 2.2000],
       device='cuda:0'))
(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 1.1000, 2.1000, 3.1000],
       device='cuda:0'), tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.2000, 1.2000, 2.2000, 3.2000],
       device='cuda:0'))
(tensor([0.0000, 0.0000, 0.0000, 0.1000, 1.1000, 2.1000, 3.1000, 4.1000],
       device='cuda